/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package homework


import spock.lang.Specification
import spock.lang.Subject

class CommandLineApplicationSpec extends Specification {

    static final String SUCCESS_MESSAGE = "Everything is fine"
    static final String FAILURE_MESSAGE = "Wrong parameters"

    Converter converter = Mock()

    @Subject
    CommandLineApplication application = new CommandLineApplication(converter)

    def "application executed with correct parameters and printed output"() {
        given:
            String[] params = []
            converter.convert(params) >> createSuccessExecutionResultMock()
        when:
            application.execute(params)
        then:
            // TODO fix this
            0 * application.printSuccessMessage(SUCCESS_MESSAGE)
    }

    private ExecutionResult createSuccessExecutionResultMock() {
        Mock(ExecutionResult) {
            isSuccess() >> true
            getSuccessMessage() >> SUCCESS_MESSAGE
        }
    }

    private ExecutionResult createFailureExecutionResultMock() {
        Mock(ExecutionResult) {
            isSuccess() >> false
            getErrorMessage() >> FAILURE_MESSAGE
        }
    }
}
