/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package homework


import spock.lang.Specification
import spock.lang.Subject

class CommandLineApplicationSpec extends Specification {

    static final String CONVERTED_VALUE = "555.333"
    static final String FAILURE_MESSAGE = "Wrong parameters"

    ConversionHandler converter = Mock()

    @Subject
    CommandLineApplication application = new CommandLineApplication(converter)
/*
    def "application executed with correct parameters and printed output"() {
        given:
            String[] params = []
            converter.convertAndPrintResult(params) >> createSuccessExecutionResultMock()
        when:
            application.execute(params)
        then:
            // TODO fix this
            0 * application.printSuccessMessage(CONVERTED_VALUE)
    }

    private ConversionResult createSuccessExecutionResultMock() {
        Mock(ConversionResult) {
            isSuccess() >> true
            getConvertedValue() >> CONVERTED_VALUE
        }
    }

    private ConversionResult createFailureExecutionResultMock() {
        Mock(ConversionResult) {
            isSuccess() >> false
            getErrorMessage() >> FAILURE_MESSAGE
        }
    }
    */

}
