/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

import homework.argument.ArgumentWrapper;
import homework.rate.HardcodedRateProvider;
import homework.rate.RateProvider;

import java.math.MathContext;
import java.util.Locale;

import static java.math.MathContext.DECIMAL64;

public class CommandLineApplication {

    private static final MathContext MATH_OPERATIONS_CONTEXT = DECIMAL64;
    private static final int CURRENCY_SCALE = 2;
    private static final Locale DEFAULT_LOCALE = Locale.forLanguageTag("da-DK");
    private static final String DEFAULT_CURRENCY_CODE = "DKK";
    private static final RateProvider RATE_PROVIDER = new HardcodedRateProvider();

    public static void main(String[] args) {
        // TODO Maybe to use converter factory ?
        new ConversionHandler().convertAndPrintResult(new ArgumentWrapper(args));
    }
}
