/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

import homework.rate.HardcodedRateProvider;
import homework.rate.RateProvider;

import java.math.MathContext;
import java.util.Locale;

import static java.math.MathContext.DECIMAL64;

public class CommandLineApplication {

    private static final MathContext MATH_OPERATIONS_CONTEXT = DECIMAL64;
    private static final int CURRENCY_PRECISION = 2;
    private static final Locale DEFAULT_LOCALE = Locale.forLanguageTag("da-DK");
    private static final String DEFAULT_CURRENCY_CODE = "DKK";
    private static final RateProvider RATE_PROVIDER = new HardcodedRateProvider();

    private CommandLineConverter converter;

    public CommandLineApplication(CommandLineConverter converter) {
        this.converter = converter;
    }

    public static void main(String[] args) {

        // TODO Maybe to use converter factory ?
        CommandLineConverter converter = new CommandLineConverter(MATH_OPERATIONS_CONTEXT, CURRENCY_PRECISION, DEFAULT_LOCALE, DEFAULT_CURRENCY_CODE, RATE_PROVIDER);

        new CommandLineApplication(converter).execute(args);
    }

    public void execute(String[] args) {
        ExecutionResult result = converter.convert(args);
        if (result.isSuccess()) {
            printSuccessMessage(result.getSuccessMessage());
        } else {
            printErrorMessage(result.getErrorMessage());
        }
    }

    public void printSuccessMessage(String message) {
        //System.out.println(message);
        String xxx = "";
    }

    public void printErrorMessage(String message) {
        //System.err.println(message);
    }
}
