/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

import homework.argument.ArgumentWrapper;
import homework.argument.Validator;
import homework.argument.ValidatorFactory;
import homework.currency.Converter;
import homework.currency.ConverterFactory;
import homework.printer.Printer;
import homework.printer.PrinterFactory;
import homework.rate.RateProvider;
import homework.rate.RateProviderFactory;

public class CommandLineApplication {
    public static void main(String[] args) {
        RateProvider rateProvider = new RateProviderFactory().getRateProvider();
        Validator validator = new ValidatorFactory().getValidator(rateProvider);
        Converter converter = new ConverterFactory().getConverter(rateProvider);
        Printer printer = new PrinterFactory().getPrinter();

        new ConversionHandler(validator, converter, printer).convertAndPrintResult(new ArgumentWrapper(args));
    }
}
